django_app/django_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('seedstars.urls')),
]

django_app/seedstars/urls.py
from django.conf.urls import url

from . import views

app_name = 'seedstars'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add$', views.AddView.as_view(), name='add'),
    url(r'^list$', views.ListView.as_view(), name='list')
]

django_app/seedstars/models.py
from __future__ import unicode_literals

from django.db import models


class Person(models.Model):
    email = models.EmailField(max_length=150, primary_key=True)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.email

django_app/seedstars/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Person


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ('email', 'name',)

django_app/seedstars/views.py
from django.shortcuts import render
from django.views import generic

from .models import Person
from .forms import PersonForm


class IndexView(generic.TemplateView):
    template_name = "seedstars/index.html"


class ListView(generic.View):
    model = Person
    template_name = 'seedstars/list.html'

    def get(self, request):
        person_list = Person.objects.all()
        context = {'persons' : person_list}
        return render(request, self.template_name, context)


class AddView(generic.View):

    form_class = PersonForm
    template_name = 'seedstars/add.html'

    context = {}
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        self.context = {'form' : form}
        return render(request, self.template_name, self.context)

    def post(self, request):
        form = self.form_class(request.POST)
        self.context = {'form' : form}
        if form.is_valid():
            form.save(commit=True)
            self.context['success_message'] = "Record Successfully Added!"
            return render(request, self.template_name, self.context)

        return render(request, self.template_name, self.context)

django_app/seedstars/templates/_header.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Seedstars Django Challenge</a>
    </div>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'seedstars:index' %}"><strong>HOME</strong></a></li>
        <li><a href="{% url 'seedstars:add' %}"><strong>ADD</strong></a></li>
        <li><a href="{% url 'seedstars:list' %}"><strong>LIST</strong></a></li>
      </ul>
  </div><!-- /.container-fluid -->
</nav>

django_app/seedstars/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <title>{% block title %}Seedstars Challenge{% endblock %}</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block meta %}{% endblock %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    {% block head %}{% endblock %}
  </head>

<body>
    <div class="container">
        <header>
            {% include "_header.html" %}
        </header>

        {% block container %}
        {% endblock %}

        <footer>
            {% include "_footer.html" %}
        </footer>
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}

</body>
</html>

django_app/seedstars/templates/seedstars/add.html
{% extends 'base.html' %}

{% block container %}
<div class="main-block">

        {% if success_message %}<p><span class="alert alert-success">{{ success_message }}</span></p>{% endif %}

    <form action="{% url 'seedstars:add' %}" method="POST">
    {% csrf_token %}
        {{ form.as_p }}
        <!--input class="form-control" type="email" name="email" placeholder="Email Address" /><br/>
        <input class="form-control" type="text" name="name" placeholder="Full Name" /><br/-->
        <input class="btn btn-primary form-control thin" type="submit" value="Add" />
    </form>
</div>
{% endblock %}

django_app/seedstars/templates/seedstars/index.html
{% extends 'base.html' %}

{% block container %}
<div class="main-block">
    <div>
        <h2>Welcome!</h2>
    </div>
    <span class="options">
        <a class="btn btn-primary" href="{% url 'seedstars:add' %}">Add</a>
        <a class="btn btn-default" href="{% url 'seedstars:list' %}">List</a>
    </span>
</div>
{% endblock %}

django_app/seedstars/templates/seedstars/list.html
{% extends 'base.html' %}

{% block container %}
{% if persons.count > 0 %}
<div class="panel panel-default">
  <div class="panel-heading">Records</div>
  <table class="table">
    {% for person in persons %}
    <tr><td><span>{{person.email}}</span></td>
        <td><span>{{person.name}}</span></td></tr>
    {% endfor %}
  </table>
</div>
{% else %}
<div class="main-block">
  <p><span class="alert alert-info">You have no stored records yet</span></p>
</div>
{% endif %}
{% endblock %}